### ISSUE TITLE
Should the recurringEvent parameter in your example be true?

### ISSUE THREAD

**Issue by stevevance** [bvacchiano/youthideashack#1]
From the Clearpath API documentation it says that the ````recurringEvent```` parameter is optional, and a value of true means that the tip you're submitting is a recurring incident.

**Comment by bvacchiano** [comment]
Hey Steve - if you're submitting a tip that's a recurring event, you can enter a recurringEvent url parameter and it's values will be either "yes" or "no"

![image](https://cloud.githubusercontent.com/assets/4966770/12072124/aa78cc14-b096-11e5-8818-3e3440a639c5.png)

**Comment by stevevance** [comment]
I originally misunderstood what this parameter meant. 
It means, "This tip is regarding something that happens repeatedly", right?

**Comment by bvacchiano** [comment]
Yeah. For instance, you may see the same group of people hanging out at the park doing some shady business when you walk your dog every morning. (Hypothetically - not sure if you do or don't have a dog 🐩 or if you go to the park every morning😁)

__________________
Brittany Vacchiano
M: 773.860.5010
bhvacchiano@gmail.com
